export const SET_STOP_ID = 'SET_STOP_ID';
export const SET_LINE_ID = 'SET_LINE_ID';

export const FETCH_STOP_TIMETABLE = 'FETCH_STOP_TIMETABLE_REQUEST';
export const FETCH_STOP_TIMETABLE_SUCCESS = 'FETCH_STOP_TIMETABLE_SUCCESS';
export const FETCH_STOP_TIMETABLE_FAILURE = 'FETCH_STOP_TIMETABLE_FAILURE';

export const FETCH_LINE_TIMETABLE = 'FETCH_LINE_TIMETABLE_REQUEST';
export const FETCH_LINE_TIMETABLE_SUCCESS = 'FETCH_LINE_TIMETABLE_SUCCESS';
export const FETCH_LINE_TIMETABLE_FAILURE = 'FETCH_LINE_TIMETABLE_FAILURE';