export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const FETCH_GOOGLE_RESULTS = 'FETCH_GOOGLE_RESULTS';
export const FETCH_GOOGLE_RESULTS_SUCCESS = 'FETCH_GOOGLE_RESULTS_SUCCESS';
export const FETCH_GOOGLE_RESULTS_FAILURE = 'FETCH_GOOGLE_RESULTS_FAILURE';

